In 711 handle multiple configs - Part 6
eastgenomics/eggd_conductor pull request #130
Opened 2024-09-03 10:16 UTC by Yu-jinKim

- Rename DX parameters and appropriate changes in the bash code
- Fix a lot of errors
- Fix using the config assay code rather than the actual config dict
- FIx some imports

2024-09-03 10:16 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/run_workflows/run_workflows.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/run_workflows.py):

> [Line 673:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/run_workflows.py#L673): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

* In the file [`resources/home/dnanexus/run_workflows/utils/dx_requests.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py):

> [Line 88:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L88): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 89:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L89): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 129:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L129): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 369:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L369): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 430:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L430): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 780:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L780): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 887:80](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L887): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)



* In the file [`resources/home/dnanexus/run_workflows/utils/manage_dict.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/manage_dict.py):

> [Line 16:1](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L16): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 17:1](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L17): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2024-09-03 10:37 UTC, jethror1 requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/130)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 488 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/130#-O5rRp150qpeF1eQLfO3:-O5rRp164jp8po0HUsJA:b-8jw8tb) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/run_workflows.py#L488)):*
> ```Python
>         run_id = args.dx_project_id
>     else:
>         run_id = args.run_id
> ```

not sure what your aim is here but I am confused, if there's no project ID specified then you're setting the run ID to also be none? 



_Code quote:_
```Python
    if not args.dx_project_id:
        # output project not specified, create new one from run id
        run_id = args.dx_project_id
    else:
        run_id = args.run_id
```


<!-- Sent from Reviewable.io -->

2024-09-04 08:57 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/130)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 488 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/130#-O5rRp150qpeF1eQLfO3:-O5wF89F4ejmYHGikxtk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b63b4876e4c6f6e202b2a6006f64edbce57012e/resources/home/dnanexus/run_workflows/run_workflows.py#L488)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not sure what your aim is here but I am confused, if there's no project ID specified then you're setting the run ID to also be none?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 09:13 UTC, jethror1 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-09-04 09:13 UTC, merged