In 711 handle multiple configs - Part 9
eastgenomics/eggd_conductor pull request #133
Opened 2024-09-18 13:51 UTC by Yu-jinKim

- New `demultiplexing.py` script to organise demultiplexing related functions
- Rename `request_objects.py` to `WebClasses.py`
- Rename `dx_requests.py` to `AssayHandler.py`
- Refactor AssayHandler to have one object per assay detected in the run
- Refactor main to use the new AssayHandler
- Move functions related with DNAnexus to `dx_utils.py`: terminate_jobs and dx_run

2024-09-18 13:51 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/run_workflows/run_workflows.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py):

> [Line 165:80](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L165): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 771:80](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L771): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`resources/home/dnanexus/run_workflows/utils/AssayHandler.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/AssayHandler.py):

> [Line 376:80](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/AssayHandler.py#L376): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 436:80](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/AssayHandler.py#L436): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)







* In the file [`resources/home/dnanexus/run_workflows/utils/manage_dict.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/manage_dict.py):

> [Line 17:1](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L17): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

* In the file [`resources/home/dnanexus/run_workflows/utils/utils.py`](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/utils.py):

> [Line 15:1](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/utils/utils.py#L15): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2024-09-18 15:03 UTC, jethror1 requested changes
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 504 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133#-O74SrvSB-jrFz1qcYak:-O74SrvSB-jrFz1qcYal:b-9unw6p) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L504)):*
> ```Python
>     run_time = time_stamp()
> 
> # -----------------------------------------------------------------------------
> ```

delete?



_Code quote:_
```Python
# -----------------------------------------------------------------------------
```
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 606 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133#-O74dqvk9bFo5kQH75RV:-O74dqvk9bFo5kQH75RW:b-yxgrts) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L606)):*
> ```Python
>                 Slack().send(error)
> 
> # -----------------------------------------------------------------------------
> ```

also delete?



_Code quote:_
```Python
# -----------------------------------------------------------------------------
```
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 690 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133#-O74dt3O60LJIdCljGuC:-O74dt3O60LJIdCljGuD:b-yjg231) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L690)):*
> ```Python
>         )
> 
> # -----------------------------------------------------------------------------
> ```

and this?



_Code quote:_
```Python
---------------------------------------------------------------------------
```


<!-- Sent from Reviewable.io -->

2024-09-20 10:29 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 504 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133#-O74SrvSB-jrFz1qcYak:-O7DydyK76Bk5I3QKcR2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L504)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

delete?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 606 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133#-O74dqvk9bFo5kQH75RV:-O7DyeKy44gcEWr0M0fP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L606)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

also delete?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 690 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133#-O74dt3O60LJIdCljGuC:-O7Dyeof8WH9VSVcR2MH:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8b6952b4fcf8a6def7281b5d9dbe2af4457ac1dd/resources/home/dnanexus/run_workflows/run_workflows.py#L690)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

and this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-20 14:28 UTC, jethror1 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-09-20 14:29 UTC, merged