Part 18: In 713 handle cancelling of jobs depending of which config is concerned
eastgenomics/eggd_conductor pull request #142
Opened 2024-10-28 15:33 UTC by Yu-jinKim

- massive try/except block in order to keep the job starts from failing if one of the assays has issues
- remove the total job file
- add the number of jobs started to the analysis project log file
- move job reuse checking to `utils.py`
- fix job termination bug in bash
- adjust slack summary message of jobs started

![image](https://github.com/user-attachments/assets/5d3da945-1580-4d09-aae7-fb61a2a41e21)

2024-10-28 15:33 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/run_workflows/run_workflows.py`](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py):

> [Line 576:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L576): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 589:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L589): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 593:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L593): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 602:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L602): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 613:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L613): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 635:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L635): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 636:80](https://github.com/eastgenomics/eggd_conductor/blob/c0f1530d4b589473681cc795e563e40987d913ea/resources/home/dnanexus/run_workflows/run_workflows.py#L636): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2024-10-28 15:50 UTC, jethror1 requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`src/eggd_conductor.sh` line 372 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142#-OAIoLc97a4CjmFbx5-T:-OAIoLc97a4CjmFbx5-U:beigp2o) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/54637f378c919a79f52957f5a6dadac793d1e7b7/src/eggd_conductor.sh#L372)):*
> ```Shell
>     }
> 
>     message=":receipt: eggd_conductor:"
> ```

why no `:white_check:` for completed running?



_Code quote:_
```Shell
:receipt:
```
___
*[`src/eggd_conductor.sh` line 385 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142#-OAIo3_J5nVKNl2OBUy4:-OAIo3_J5nVKNl2OBUy5:b3n9r8t) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/54637f378c919a79f52957f5a6dadac793d1e7b7/src/eggd_conductor.sh#L385)):*
> ```Shell
> 
>         message+="Analysis project: *${project_name}*%0A${analysis_project_url}%0A"
>         message+="Config used: *${assay}* (v${version})"
> ```

can this be the file name and not the codes since they're not that useful. also some line breaks / bullet points and bolding pls like it currently has to make it easier to read



_Code quote:_
```Shell
assay
```


<!-- Sent from Reviewable.io -->

2024-10-30 09:53 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`src/eggd_conductor.sh` line 372 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142#-OAIoLc97a4CjmFbx5-T:-OAIpsX96LuPXlZDyMwB:bfgk7n) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/54637f378c919a79f52957f5a6dadac793d1e7b7/src/eggd_conductor.sh#L372)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why no `:white_check:` for completed running?
</blockquote></details>

it's not a completed running message anymore since errors can occur for one assay
___
*[`src/eggd_conductor.sh` line 385 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142#-OAIo3_J5nVKNl2OBUy4:-OARq1mUCfJI7f89kwLr:b-y21nqd) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/54637f378c919a79f52957f5a6dadac793d1e7b7/src/eggd_conductor.sh#L385)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be the file name and not the codes since they're not that useful. also some line breaks / bullet points and bolding pls like it currently has to make it easier to read
</blockquote></details>

added file ids instead


<!-- Sent from Reviewable.io -->

2024-10-30 10:59 UTC, jethror1 approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-10-30 11:09 UTC, merged