Part 19: In 806 various fixes
eastgenomics/eggd_conductor pull request #143
Opened 2024-10-31 16:09 UTC by Yu-jinKim

- Match version from wheels to requirements.txt
- dx_project_id is False by default
- Keep only handlers that have samples associated
- Bug fixes for ticket handling
- add parameter to `write job summaries`
- improve formatting of job summary file
- fix upload of job summary file + rename file to remove the project name from the filename

2024-10-31 16:09 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`resources/home/dnanexus/run_workflows/utils/utils.py`](https://github.com/eastgenomics/eggd_conductor/blob/1b97fdf93010044e21706be39cabaa43263c76d7/resources/home/dnanexus/run_workflows/utils/utils.py):

> [Line 655:80](https://github.com/eastgenomics/eggd_conductor/blob/1b97fdf93010044e21706be39cabaa43263c76d7/resources/home/dnanexus/run_workflows/utils/utils.py#L655): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 659:80](https://github.com/eastgenomics/eggd_conductor/blob/1b97fdf93010044e21706be39cabaa43263c76d7/resources/home/dnanexus/run_workflows/utils/utils.py#L659): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 671:80](https://github.com/eastgenomics/eggd_conductor/blob/1b97fdf93010044e21706be39cabaa43263c76d7/resources/home/dnanexus/run_workflows/utils/utils.py#L671): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 79 characters)
> [Line 711:80](https://github.com/eastgenomics/eggd_conductor/blob/1b97fdf93010044e21706be39cabaa43263c76d7/resources/home/dnanexus/run_workflows/utils/utils.py#L711): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)

2024-11-01 09:53 UTC, jethror1 requested changes
> Reviewed 4 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/143)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/utils/WebClasses.py` line 186 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor/143#-OAb8-S-AlntMSNtEHfN:-OAb8-S-AlntMSNtEHfO:bbwshkc) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/62dcde2c03697bc9c6cf28e58acd54e0f2d5c74a/resources/home/dnanexus/run_workflows/utils/WebClasses.py#L186)):*
> ```Python
>             # has not yet been raised / forgotten about, send an alert and
>             # continue with things since linking to Jira is non-essential
>             self.send_slack_alert(
> ```

is this done somewhere else?


<!-- Sent from Reviewable.io -->

2024-11-01 09:55 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/143)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/utils/WebClasses.py` line 186 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor/143#-OAb8-S-AlntMSNtEHfN:-OAb8WuE1-M7Q_Dn8CTa:b1a1jns) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/62dcde2c03697bc9c6cf28e58acd54e0f2d5c74a/resources/home/dnanexus/run_workflows/utils/WebClasses.py#L186)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this done somewhere else?
</blockquote></details>

yes https://github.com/eastgenomics/eggd_conductor/blob/IN-806-Various-fixes/resources/home/dnanexus/run_workflows/run_workflows.py#L404


<!-- Sent from Reviewable.io -->

2024-11-01 10:44 UTC, jethror1 approved these changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/143)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-11-01 10:44 UTC, merged