v1.4.0 - fix tso500 reports launch
eastgenomics/eggd_conductor pull request #99
Opened 2024-01-12 17:09 UTC by jethror1

- fix for querying TSO500 jobs with a missing output field (i.e. all DNA samples => expected no RNA outputs)
- handle spaces in 

- example launching all DNA samples:
![image](https://github.com/eastgenomics/eggd_conductor/assets/45037268/47dcfe2f-b316-4029-af88-3eec635b240b)

- example of space in `-iJOB_REUSE` input:
![image](https://github.com/eastgenomics/eggd_conductor/assets/45037268/7c4d7133-89e4-4705-a0a8-19049b336036)

2024-01-12 17:35 UTC, pep8speaks commented
Hello @jethror1! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py`](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py):

> [Line 449:13](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L449): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 451:13](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L451): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 453:13](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L453): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 455:13](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L455): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 460:80](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L460): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 472:18](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L472): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent
> [Line 481:18](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L481): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

2024-01-15 09:39 UTC, Yu-jinKim requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 472 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99#-NoBU7oH65bjqXtdcvQe:-NoBU7oH65bjqXtdcvQf:b2m4i08) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L472)):*
> ```Python
>             self.assertEqual(
>                 output['stage-G0qpXy0433Gv75XbPJ3xj8jV.reads_fastqgzs'],
>                  [
> ```

is there a space on this line? it looks weird
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 481 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99#-NoBUCThB76uCetzXkk1:-NoBUCTi70r1_F2bWeT4:b-2guby3) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L481)):*
> ```Python
>             self.assertEqual(
>                 output['stage-G0qpXy0433Gv75XbPJ3xj8jV.reads2_fastqgzs'],
>                  [
> ```

same here


<!-- Sent from Reviewable.io -->

2024-01-15 10:48 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 472 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99#-NoBU7oH65bjqXtdcvQe:-NoBj92VDToPArnVUQCJ:ba4qp54) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L472)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is there a space on this line? it looks weird
</blockquote></details>

so there was, 10 points to your eyes
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 481 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99#-NoBUCThB76uCetzXkk1:-NoBjAwl-r2r5Zhb9gdu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8c43ec2c84de4a37f12bbfd57785ad788cd704e8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L481)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-15 10:59 UTC, Yu-jinKim approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-01-15 10:59 UTC, merged